---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/picpix/
    - /bin/rm $DEPLOYPATH/* -Rf
    - /bin/cp -R * $DEPLOYPATH
    - source $HOME/nodevenv/lan/24/bin/activate && cd $DEPLOYPATH
    - npm install
    - npm run lint
    - npm test
    - mkdir -p tmp
    - touch tmp/restart.txt
